services:
  _defaults:
    public: true  

  prestashop.module.migratorvmps.mainrepository:
    class: Migratorvmps\Repository\MainRepository   
    arguments:
      $connection: '@doctrine.dbal.default_connection'
           
  prestashop.module.migratorvmps.insertimagerepository:
    class: Migratorvmps\Repository\InsertImageRepository   
    arguments:
      $connection: '@doctrine.dbal.default_connection'